name: tutorials
description: "Tutoriales Flutter en español para todos los niveles (básico, intermedio y avanzado)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_gen: ^5.6.0
  flutter_svg: ^2.0.4
  go_router: ^14.2.3

  basic_module:
    path: ../../modules/basic_module
  intermediate_module:
    path: ../../modules/intermediate_module
  advanced_module:
    path: ../../modules/advanced_module
  other_module:
    path: ../../modules/other_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.6.0

flutter_gen:
  output: lib/presenter/gen
  assets:
    outputs:
      package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/